/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Boat {
  heyWow?: HeyWow;
  someFeatures?: SomeFeatures;
  theRichTextDesc?: MarkdownFile;
}
/**
 * Wow this brand must be expensive
 */
export interface HeyWow {
  /**
   * Wow this brand must be expensive
   */
  model: string;
  /**
   * Not too old, not too new
   */
  year: number;
}
/**
 * Wow this brand must be expensive
 */
export interface SomeFeatures {
  /**
   * Wow this brand must be expensive
   */
  model: string;
  /**
   * Not too old, not too new
   */
  year: number;
  /**
   * Peemp it
   */
  color: "red" | "green" | "blue";
  /**
   * Wiw it!!
   */
  brand: "dou" | "bi" | "douda";
}
export interface MarkdownFile {
  headings?: string;
  body: string;
  excerpt?: string;
}
