/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Dessert {
  frontmatter?: {
    /**
     * Wow this brand must be expensive
     */
    name?: string;
    /**
     * Not too old, not too new
     */
    calories?: number;
    /**
     * Peemp it
     */
    color?: "red" | "green" | "blue";
    /**
     * Peemp it
     */
    taste: "awful" | "exquisite" | "meh" | "wow";
  };
  body?: MarkdownFile;
  [k: string]: unknown;
}
export interface MarkdownFile {
  headings?: string;
  body: string;
  excerpt?: string;
}
