/* AUTO-GENERATED BY `@astro-content/validator`. Do not edit! */

import { itemChecker } from '@astro-content/validator';

const schema = {"title":"Blog post","allOf":[{"$ref":"./tags.schema.yaml"},{"properties":{"title":{"title":"Title","default":"My untitled blog post","description":"Used for SEO and tab title!","type":"string","minLength":1,"maxLength":80},"description":{"title":"Description","default":"No description found.","description":"Used for SEO","type":"string","minLength":100,"maxLength":300}},"required":["title","description"]}]}
export { schema };

export type BlogPost = TagsSchema & {
  title: Title;
  description: Description;
  [k: string]: unknown;
};
/**
 * Used for SEO and tab title!
 */
export type Title = string;
/**
 * Used for SEO
 */
export type Description = string;

export interface TagsSchema {
  /**
   * @minItems 1
   * @maxItems 8
   */
  tags?:
    | ["Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport"]
    | [
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport"
      ]
    | [
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport"
      ]
    | [
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport"
      ]
    | [
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport"
      ]
    | [
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport"
      ]
    | [
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport"
      ]
    | [
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport"
      ];
  [k: string]: unknown;
}

export function checkBlogPost(item: unknown) {
  return itemChecker<BlogPost>(item, 'src/schemas/blog-post.schema.yaml');
}
