/* AUTO-GENERATED BY `@astro-content/validator`. Do not edit! */

import { itemChecker } from '@astro-content/validator';

const schema = {"properties":{"tags":{"type":"array","uniqueItems":true,"minItems":1,"maxItems":8,"items":{"type":"string","enum":["Music","Video","Development","Cooking","Gardening","Sport"]}}}}
export { schema };

export interface Tags {
  /**
   * @minItems 1
   * @maxItems 8
   */
  tags?:
    | ["Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport"]
    | [
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport"
      ]
    | [
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport"
      ]
    | [
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport"
      ]
    | [
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport"
      ]
    | [
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport"
      ]
    | [
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport"
      ]
    | [
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport",
        "Music" | "Video" | "Development" | "Cooking" | "Gardening" | "Sport"
      ];
  [k: string]: unknown;
}

export function checkTags(item: unknown) {
  return itemChecker<Tags>(item, 'src/schemas/tags.schema.yaml');
}
