/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Boat {
  /**
   * Wow this brand must be expensive
   */
  model?: string;
  /**
   * Not too old, not too new
   */
  year: number;
  /**
   * Peemp it
   */
  color?: "red" | "green" | "blue";
  /**
   * Peemp it
   */
  brand?: "dou" | "bi" | "douda";
  [k: string]: unknown;
}
