import { compile, JSONSchema } from 'json-schema-to-typescript';
/* ·········································································· */
import markdownFile from './schemas/MarkdownFile.json' assert { type: 'json' };
/* —————————————————————————————————————————————————————————————————————————— */

export default async function schemaToTypes(schema: JSONSchema) {
  let type = '';

  const schemaForTs = {
    definitions: {
      MarkdownFile: markdownFile as JSONSchema,
    },
    ...schema,
  };

  await compile(schemaForTs, 'untitled')
    .then((ts) => {
      // eslint-disable-next-line @typescript-eslint/no-use-before-define
      type = ts.replace(header, '');
    })
    .catch((e) => console.error(e));

  return type;
}

const header = `/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

`;
