name: Deploy — [Docs]

on: 'push'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      # ————————————————————————————————————————————————————————————————————————

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # ————————————————————————————————————————————————————————————————————————

      - name: Setup PNPM 7
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.9.0
          run_install: false

      - name: Get PNPM store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup PNPM cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # ————————————————————————————————————————————————————————————————————————

      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-

      # ————————————————————————————————————————————————————————————————————————

      - name: Install Node dependencies
        # `NODE_ENV=production` to exclude dev. dependencies
        run: pnpm --recursive install --frozen-lockfile

      - name: Install Puppeteer
        run: cd ./node_modules/puppeteer && node install.js

      # NOTE: It's all built together now (see below).
      # - name: Build Astro Website
      #   # working-directory: ./docs
      #   run: cd ./docs && pnpm run build

      - name: Build the whole mono-repository
        run: pnpm run build

      # ————————————————————————————————————————————————————————————————————————
      # BRANCH

      - name: Generate Netlify alias
        if: contains(github.ref, 'master') == false
        shell: bash
        run: ruby -e 'puts "::set-output name=netlify_alias::#{`git branch --show-current`.chomp.gsub(/[^a-zA-Z\d]/){"-"}.downcase}"'
        id: get_netlify_alias

      - name: Deploy to Netlify (branch)
        if: contains(github.ref, 'master') == false
        uses: nwtgck/actions-netlify@v1.2.3
        with:
          alias: ${{ steps.get_netlify_alias.outputs.netlify_alias }}
          github-deployment-environment: ${{ steps.get_netlify_alias.outputs.netlify_alias }}

          publish-dir: './docs/dist'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy [branch] from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: false
          enable-commit-status: false
          overwrites-pull-request-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

      # ————————————————————————————————————————————————————————————————————————
      # PRODUCTION

      - name: Deploy [Docs] to Netlify
        if: contains(github.ref, 'master')
        uses: nwtgck/actions-netlify@v1.2.3
        with:
          production-branch: master

          publish-dir: './docs/dist'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy [master] from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: false
          enable-commit-status: false
          overwrites-pull-request-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
